services:
  frontend:
    image: ghcr.io/gustavo-dms/tcc-front:${GIT_COMMIT_HASH:-latest}
    environment:
      NODE_ENV: production
    ports:
      - 3001:3000
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db

  db:
    image: ghcr.io/gustavo-dms/tcc-db:${GIT_COMMIT_HASH:-latest}
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/gustavo-dms/tcc-backend:${GIT_COMMIT_HASH:-latest}
    secrets:
      - db-password
    ports:
      - 4000:4000
    environment:
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_URL=postgres://postgres:${DATABASE_PASSWORD}@db:5432/mydb
      - FLASK_DEBUG=1

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=teste@teste.com.br
      - PGADMIN_DEFAULT_PASSWORD=Teste123
    ports:
      - 16543:80

volumes:
  db-data:

secrets:
  db-password:
    external: true
