services:
  frontend:
    image: ghcr.io/gustavo-dms/tcc-front:${GIT_COMMIT_HASH:-latest}
    environment:
      NODE_ENV: production
      AUTH_TRUST_HOST: 1
      AUTH_SECRET: RByw/uPDRceFerQV91wnmet/pBo+44jb3eVz3bXvlv4=
    ports:
      - 3001:3000
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db

  db:
    image: ghcr.io/gustavo-dms/tcc-db:${GIT_COMMIT_HASH:-latest}
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/gustavo-dms/tcc-backend:${GIT_COMMIT_HASH:-latest}
    secrets:
      - db-password
      - db-url
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=/run/secrets/db-url
      - DATABASE_PASSWORD=/run/secrets/db-password
    deploy:
      update_config:
        order: start-first

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=teste@teste.com.br
      - PGADMIN_DEFAULT_PASSWORD=Teste123
    ports:
      - 16543:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:

secrets:
  db-password:
    external: true
  db-url:
    external: true
