BEGIN;


CREATE TABLE IF NOT EXISTS public.rl_paciente_cid
(
    id_paciente integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_cid integer NOT NULL,
    CONSTRAINT rl_paciente_cid_pkey PRIMARY KEY (id_paciente)
);

CREATE TABLE IF NOT EXISTS public.rl_paciente_terminal_beiraleito
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_paciente integer NOT NULL,
    id_terminal integer NOT NULL,
    ativo boolean NOT NULL,
    dt_ativacao timestamp without time zone NOT NULL,
    dt_desativacao timestamp without time zone,
    CONSTRAINT rl_paciente_terminal_beiraleito_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_caixa_transporte
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    descricao character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dt_ativacao timestamp without time zone NOT NULL,
    dt_desativacao time with time zone,
    ativo boolean NOT NULL,
    CONSTRAINT tb_caixa_transporte_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_cargo
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    descricao character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_cargo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_cid
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    descricas character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_cid_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_classe_terapeutica
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_classe_terapeutica_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_estoque
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_medicamento integer NOT NULL,
    quantidade_atual integer NOT NULL,
    uuid uuid NOT NULL,
    dt_registro timestamp without time zone NOT NULL,
    d_vencimento date NOT NULL,
    CONSTRAINT tb_estoque_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_funcionario
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_cargo integer NOT NULL,
    ativo boolean NOT NULL,
    dt_ativacao date NOT NULL,
    dt_desativacao date,
    CONSTRAINT tb_funcionario_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_historico_estoque
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_estoque integer NOT NULL,
    dt_consumo_beiraleito timestamp without time zone,
    id_funcionario integer NOT NULL,
    id_terminal_origem integer NOT NULL,
    id_terminal_destino integer NOT NULL,
    quantidade integer NOT NULL,
    dt_saida_farmacia timestamp without time zone NOT NULL,
    id_caixa_transporte integer NOT NULL,
    CONSTRAINT tb_historico_estoque_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_medicamento
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    cod_anvisa integer NOT NULL,
    id_classe_terapeutica integer NOT NULL,
    apresetacao character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_tarja integer NOT NULL,
    dt_ativacao timestamp without time zone NOT NULL,
    dt_desativacao timestamp without time zone,
    ativo boolean NOT NULL,
    CONSTRAINT tb_medicamento_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_paciente
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    d_nascimento date NOT NULL,
    CONSTRAINT tb_paciente_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_tarja
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    descricao character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_tarja_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_terminal
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    descricao character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dt_ativacao timestamp without time zone NOT NULL,
    dt_desativacao timestamp without time zone,
    ativo boolean NOT NULL,
    CONSTRAINT tb_terminal_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.rl_paciente_cid
    ADD FOREIGN KEY (id_paciente)
    REFERENCES public.tb_paciente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rl_paciente_cid
    ADD FOREIGN KEY (id_cid)
    REFERENCES public.tb_cid (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rl_paciente_terminal_beiraleito
    ADD FOREIGN KEY (id_paciente)
    REFERENCES public.tb_paciente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rl_paciente_terminal_beiraleito
    ADD FOREIGN KEY (id_terminal)
    REFERENCES public.tb_terminal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb_estoque
    ADD FOREIGN KEY (id_medicamento)
    REFERENCES public.tb_medicamento (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb_funcionario
    ADD FOREIGN KEY (id_cargo)
    REFERENCES public.tb_cargo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb_historico_estoque
    ADD FOREIGN KEY (id_estoque)
    REFERENCES public.tb_estoque (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb_historico_estoque
    ADD FOREIGN KEY (id_funcionario)
    REFERENCES public.tb_funcionario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb_historico_estoque
    ADD FOREIGN KEY (id_terminal_origem)
    REFERENCES public.tb_terminal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb_historico_estoque
    ADD FOREIGN KEY (id_terminal_destino)
    REFERENCES public.tb_terminal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb_historico_estoque
    ADD FOREIGN KEY (id_caixa_transporte)
    REFERENCES public.tb_caixa_transporte (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb_medicamento
    ADD FOREIGN KEY (id_classe_terapeutica)
    REFERENCES public.tb_classe_terapeutica (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb_medicamento
    ADD FOREIGN KEY (id_tarja)
    REFERENCES public.tb_tarja (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
